#!/usr/bin/env python3
"""Emit the DDL for every database object Prisma's schema language cannot express.

`prisma migrate diff` silently omits CHECK constraints and rewrites unusual
indexes (HNSW becomes btree, partial and expression indexes lose their WHERE
and their expression). A baseline generated from Prisma alone is therefore not
a faithful copy of the database — it would accept status='banana' and would
turn vector search into a sequential scan.

This reads the objects straight out of the catalog so the appendix is exact,
not retyped.

    python scripts/dump_raw_objects.py > ../prisma/migrations/0_init/raw_objects.sql
"""

import sys
from pathlib import Path

import psycopg

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "apps" / "api"))
from app.core.config import get_settings  # noqa: E402

# Indexes Prisma emits incorrectly rather than not at all. Listed explicitly so
# a new one is a deliberate addition here, not something that quietly slips in.
RAW_INDEXES = (
    "idx_paper_chunks_embedding",
    "idx_papers_project_sha256",
    "claim_verifications_unique_scope_idx",
)

CHECKS_SQL = """
SELECT rel.relname AS table_name,
       con.conname AS name,
       pg_get_constraintdef(con.oid) AS definition
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
 WHERE con.connamespace = 'public'::regnamespace
   AND con.contype = 'c'
 ORDER BY rel.relname, con.conname
"""

INDEXES_SQL = """
SELECT indexname, indexdef
  FROM pg_indexes
 WHERE schemaname = 'public' AND indexname = ANY(%s)
 ORDER BY indexname
"""


def main() -> int:
    with psycopg.connect(get_settings().database_url) as conn, conn.cursor() as cur:
        cur.execute(INDEXES_SQL, (list(RAW_INDEXES),))
        indexes = cur.fetchall()
        cur.execute(CHECKS_SQL)
        checks = cur.fetchall()

    missing = set(RAW_INDEXES) - {name for name, _ in indexes}
    if missing:
        sys.exit(f"Expected index(es) not found in the database: {sorted(missing)}")

    out = [
        "-- Objects Prisma cannot express. Generated by "
        "backend/scripts/dump_raw_objects.py — do not hand-edit.",
        "--",
        "-- `prisma migrate diff` drops every CHECK constraint and rewrites HNSW,",
        "-- partial and expression indexes into plain btrees. Without this file a",
        "-- database created from the Prisma baseline would accept invalid enum",
        "-- values and would answer vector search with a sequential scan.",
        "",
        "-- === Indexes =============================================================",
        "",
    ]
    for name, definition in indexes:
        out.append(f"DROP INDEX IF EXISTS public.{name};")
        out.append(f"{definition};")
        out.append("")

    out += [
        "-- === CHECK constraints ===================================================",
        "-- Enum-like columns (status, role, verdict, kind…) and range bounds. The",
        "-- Prisma schema documents these in comments; the database enforces them.",
        "",
    ]
    for table, name, definition in checks:
        out.append(
            f'ALTER TABLE public.{table} DROP CONSTRAINT IF EXISTS "{name}";'
        )
        out.append(
            f'ALTER TABLE public.{table} ADD CONSTRAINT "{name}" {definition};'
        )
        out.append("")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
